### ISSUE TITLE
Invite requests

### ISSUE THREAD

**Issue by GitCash** [GitCash/issues-and-feature-requests#1]
You know the drill

**Comment by alwaysAn0n** [comment]
@GitCash invite @block-spider please


--------- GitCash Tip Bot ---------
Hey @block-spider !
alwaysAn0n has invited you to help us beta test GitCash.io !

GitCash is a Bitcoin Cash tipping platform for Github.

Your account is all set up and ready for you at https://gitcash.io/login/

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash invite @singularity87 @CreativeName4 @checksum0 


--------- GitCash Tip Bot ---------
Hey @singularity87,@CreativeName4,@checksum0 !
alwaysAn0n has invited you to help us beta test GitCash.io !

GitCash is a Bitcoin Cash tipping platform for Github.

Your account is all set up and ready for you at https://gitcash.io/login/

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please invite @zander and @AlexEiden 


--------- GitCash Tip Bot ---------
Hey @zander,@AlexEiden !
alwaysAn0n has invited you to help us beta test GitCash.io !

GitCash is a Bitcoin Cash tipping platform for Github.

Your account is all set up and ready for you at https://gitcash.io/login/

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash invite our friend @bitbobb please


--------- GitCash Tip Bot ---------
Hey @bitbobb !
alwaysAn0n has invited you to help us beta test GitCash.io !

GitCash is a Bitcoin Cash tipping platform for Github.

Your account is all set up and ready for you at https://gitcash.io/login/

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash invite @AshleyMSherwood with 1000 bits!


--------- GitCash Tip Bot ---------
Hey @AshleyMSherwood !
alwaysAn0n has sent you 1000 bits in Bitcoin Cash (~ $ 0.65 )

Follow the link to claim it at

https://gitcash.io/claim/AshleyMSherwood


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash send @block-spider @singularity87 @CreativeName4 @checksum0 @Bitbobb @zander and @AlexEiden 1000 bits each!


--------- GitCash Tip Bot ---------
Hey @block-spider,@singularity87,@CreativeName4,@checksum0,@Bitbobb,@zander,@AlexEiden !
alwaysAn0n has sent you 1000 bits in Bitcoin Cash (~ $ 0.653 )

Follow the link to claim it at

https://gitcash.io/claim/block-spider

https://gitcash.io/claim/singularity87

https://gitcash.io/claim/CreativeName4

https://gitcash.io/claim/checksum0

https://gitcash.io/claim/Bitbobb

https://gitcash.io/claim/zander

https://gitcash.io/claim/AlexEiden


  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash invite @TauBone and give them 150000 satoshis to spend

**Comment by alwaysAn0n** [comment]
@GitCash invite @TauBone and give them 150000 satoshis to spend

**Comment by alwaysAn0n** [comment]
@GitCash invite @TauBone with 1000 bits!

**Comment by alwaysAn0n** [comment]
@GitCash send @block-spider 500 bits


--------- GitCash Tip Bot ---------
Hey @block-spider !
alwaysAn0n has sent you 500 bits in Bitcoin Cash (~ $ 0.3865 )

Follow the link to claim it at

https://gitcash.io/claim/block-spider


  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash invite @imcoddy with 100000 satoshis !


--------- GitCash Tip Bot ---------
Hey @imcoddy !
alwaysAn0n has sent you 100000 satoshis in Bitcoin Cash (~ $ 0.774 )

Follow the link to claim it at

https://gitcash.io/claim/imcoddy


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash invite @i14g  @cyio @ardiya @supercody and @TheTRUEHoohah with 100000 satoshis !

**Comment by alwaysAn0n** [comment]
@GitCash invite @i14g @ardiya @supercody and @TheTRUEHoohah with 100000 satoshis !


--------- GitCash Tip Bot ---------
Hey @i14g,@ardiya,@supercody,@TheTRUEHoohah !
alwaysAn0n has sent you 100000 satoshis in Bitcoin Cash (~ $ 0.775 )

Follow the link to claim it at

https://gitcash.io/claim/i14g

https://gitcash.io/claim/ardiya

https://gitcash.io/claim/supercody

https://gitcash.io/claim/TheTRUEHoohah


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please invite @lubokkanev with 100000 satoshis !

**Comment by alwaysAn0n** [comment]
@GitCash please invite @cashaddressio and give them 120000 satoshis

**Comment by alwaysAn0n** [comment]
@GitCash send @block-spider 500 bits

**Comment by alwaysAn0n** [comment]
@GitCash send @block-spider 500 bits


--------- GitCash Tip Bot ---------
Hey @block-spider !
alwaysAn0n has sent you 500 bits in Bitcoin Cash (~ $ 0.429 )

Follow the link to claim it at

https://gitcash.io/claim/block-spider


  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please invite @cashaddressio and give them 120000 satoshis


--------- GitCash Tip Bot ---------
Hey @cashaddressio !
alwaysAn0n has sent you 120000 satoshis in Bitcoin Cash (~ $ 1.0296 )

Follow the link to claim it at

https://gitcash.io/claim/cashaddressio


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please invite @lubokkanev with 100000 satoshis !


--------- GitCash Tip Bot ---------
Hey @lubokkanev !
alwaysAn0n has sent you 100000 satoshis in Bitcoin Cash (~ $ 0.858 )

Follow the link to claim it at

https://gitcash.io/claim/lubokkanev


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash invite @hegjon with 150000 satoshis !!


--------- GitCash Tip Bot ---------
Hey @hegjon !
alwaysAn0n has sent you 150000 satoshis in Bitcoin Cash (~ $ 1.4055 )

Follow the link to claim it at

https://gitcash.io/claim/hegjon


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please invite @Wecx with 250000 satoshis


--------- GitCash Tip Bot ---------
Hey @Wecx !
alwaysAn0n has sent you 250000 satoshis in Bitcoin Cash (~ $ 2.375 )

Follow the link to claim it at

https://gitcash.io/claim/Wecx


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by GitCash** [comment]
Public beta is over and everyone is now free to sign up without invitation.
