### ISSUE TITLE
Tipping playground

### ISSUE THREAD

**Issue by alwaysAn0n** [GitCash/issues-and-feature-requests#2]
Tip away!

**Comment by alwaysAn0n** [comment]
Hey @GitCash please send @block-spider 5000 satoshis


--------- GitCash Tip Bot ---------
Hey @block-spider !
alwaysAn0n has sent you 5000 satoshis in Bitcoin Cash (~ $ 0.0325 )

Follow the link to claim it at

https://gitcash.io/claim/block-spider


  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please invite @acelerationist and give him 2000 satoshis!


--------- GitCash Tip Bot ---------
Hey @acelerationist !
alwaysAn0n has sent you 2000 satoshis in Bitcoin Cash (~ $ 0.0155 )

Follow the link to claim it at

https://gitcash.io/claim/acelerationist


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please send @acelerationist 20000 satoshis


--------- GitCash Tip Bot ---------
Hey @acelerationist !
alwaysAn0n has sent you 20000 satoshis in Bitcoin Cash (~ $ 0.1554 )

Follow the link to claim it at

https://gitcash.io/claim/acelerationist


  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please invite @lte13 and give them 50000 satoshis to play with


--------- GitCash Tip Bot ---------
Hey @lte13 !
alwaysAn0n has sent you 50000 satoshis in Bitcoin Cash (~ $ 0.3815 )

Follow the link to claim it at

https://gitcash.io/claim/lte13


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
Hey @GitCash .  Please send @hiragashi 100000 satoshis and invite them to join us


--------- GitCash Tip Bot ---------
Hey @hiragashi !
alwaysAn0n has invited you to help us beta test GitCash.io !

GitCash is a Bitcoin Cash tipping platform for Github.

Your account is all set up and ready for you at https://gitcash.io/login/

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash invite @marfoldi and give them 100000 satoshis to play with.


--------- GitCash Tip Bot ---------
Hey @marfoldi !
alwaysAn0n has sent you 100000 satoshis in Bitcoin Cash (~ $ 0.761 )

Follow the link to claim it at

https://gitcash.io/claim/marfoldi


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please invite @Quartzic and give them 150000 satoshis to spend


--------- GitCash Tip Bot ---------
Hey @Quartzic !
alwaysAn0n has sent you 150000 satoshis in Bitcoin Cash (~ $ 1.137 )

Follow the link to claim it at

https://gitcash.io/claim/Quartzic


You were also invited to be a GitCash.io beta tester!  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash send @TauBone 150000 satoshis


--------- GitCash Tip Bot ---------
Hey @TauBone !
alwaysAn0n has sent you 150000 satoshis in Bitcoin Cash (~ $ 1.1595 )

Follow the link to claim it at

https://gitcash.io/claim/TauBone


  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash send @cyio @JustinAiken 100000 satoshis


--------- GitCash Tip Bot ---------
Hey @cyio,@JustinAiken !
alwaysAn0n has sent you 100000 satoshis in Bitcoin Cash (~ $ 0.777 )

Follow the link to claim it at

https://gitcash.io/claim/cyio

https://gitcash.io/claim/JustinAiken


  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash please send @imaginaryusername 200000 satoshis to play with


--------- GitCash Tip Bot ---------
Hey @imaginaryusername !
alwaysAn0n has sent you 200000 satoshis in Bitcoin Cash (~ $ 1.904 )

Follow the link to claim it at

https://gitcash.io/claim/imaginaryusername


  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by alwaysAn0n** [comment]
@GitCash send 550 bits to @lukeheath pretty please

**Comment by GitCash** [comment]
Hey @lukeheath !
alwaysAn0n has sent you 550 bits in Bitcoin Cash (~ $ 0.7387 )

Follow the link to claim it at

https://gitcash.io/claim/lukeheath


  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc

**Comment by alwaysAn0n** [comment]
Hey @GotCrabs please send @block-spider 5000 satoshis

**Comment by GotCrabs** [comment]
![GitCash Tip Response](https://gitcash-staging.herokuapp.com/tip/pic/36/image.png)
@block-spider

**Comment by alwaysAn0n** [comment]
@GotCrabs send @Wecx 101010 satoshis please

**Comment by GotCrabs** [comment]
[![GitCash Tip Response](https://gitcash-staging.herokuapp.com/tip/pic/22/image.png)](https://gitcash-staging.herokuapp.com/claim/Wecx)
@Wecx

**Comment by alwaysAn0n** [comment]
@GotCrabs send @imaginaryusername .0015 bch please

**Comment by GotCrabs** [comment]
[![GitCash Tip Response](https://gitcash-staging.herokuapp.com/tip/pic/23/image.png)](https://gitcash-staging.herokuapp.com/claim/imaginaryusername)
@imaginaryusername

**Comment by imaginaryusername** [comment]
woohoo i got monies i guess
@GotCrabs send @alwaysAn0n 0.0005 BCH

**Comment by alwaysAn0n** [comment]
@GotCrabs send @imaginaryusername .0008 bch please

**Comment by GotCrabs** [comment]
[![GitCash Tip Response](https://gitcash-staging.herokuapp.com/tip/pic/24/image.png)](https://gitcash-staging.herokuapp.com/claim/imaginaryusername)
@imaginaryusername

**Comment by alwaysAn0n** [comment]
@GitCash please send @RX7RUSS and @RUSSTEST 200 bits each!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/2/image.png)](https://gitcash.io/)
@RX7RUSS,@RUSSTEST

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/3/image.png)](https://gitcash.io/)
@RX7RUSS,@RUSSTEST

**Comment by GitCash** [comment]
Closing in favor of new tipping thread
