### ISSUE TITLE
Come get your tips!

### ISSUE THREAD

**Issue by GitCash** [GitCash/issues-and-feature-requests#5]
ITT: Makin' it rain Bitcoin Cash

**Comment by alwaysAn0n** [comment]
@GitCash send .03 bch to my friend @JLMoriart please!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/7/image.png)](https://gitcash.io/claim/JLMoriart)
@JLMoriart

**Comment by alwaysAn0n** [comment]
@GitCash send @JustinAiken 5916722 satoshis !

Welcome to GitCash Justin!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/9/image.png)](https://gitcash.io/claim/JustinAiken)
@JustinAiken

**Comment by alwaysAn0n** [comment]
@GitCash send @AlexEiden 100000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/10/image.png)](https://gitcash.io/claim/AlexEiden)
@AlexEiden

**Comment by alwaysAn0n** [comment]
@GitCash send @Bitbobb 100000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/11/image.png)](https://gitcash.io/claim/Bitbobb)
@Bitbobb

**Comment by alwaysAn0n** [comment]
@GitCash send @KallunaLovegood 800000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/12/image.png)](https://gitcash.io/claim/KallunaLovegood)
@KallunaLovegood

**Comment by alwaysAn0n** [comment]
@GitCash send @AshleyMSherwood 6000000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/13/image.png)](https://gitcash.io/claim/AshleyMSherwood)
@AshleyMSherwood

**Comment by alwaysAn0n** [comment]
@GitCash send @irlnathan 500000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/14/image.png)](https://gitcash.io/claim/irlnathan)
@irlnathan

**Comment by alwaysAn0n** [comment]
@GitCash send @acelerationist 500000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/15/image.png)](https://gitcash.io/claim/acelerationist)
@acelerationist

**Comment by alwaysAn0n** [comment]
@GitCash send @rachaelshaw 500000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/16/image.png)](https://gitcash.io/claim/rachaelshaw)
@rachaelshaw

**Comment by alwaysAn0n** [comment]
@GitCash send @seanwarman 1000000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/17/image.png)](https://gitcash.io/claim/seanwarman)
@seanwarman

**Comment by alwaysAn0n** [comment]
@GitCash send @lukeheath 1009530 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/18/image.png)](https://gitcash.io/claim/lukeheath)
@lukeheath

**Comment by alwaysAn0n** [comment]
@GitCash send @checksum0 100000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/19/image.png)](https://gitcash.io/claim/checksum0)
@checksum0

**Comment by alwaysAn0n** [comment]
@GitCash send @CreativeName4 50000 satoshis !

Welcome to GitCash!

**Comment by alwaysAn0n** [comment]
@GitCash send @singularity87 100000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/20/image.png)](https://gitcash.io/claim/singularity87)
@singularity87

**Comment by alwaysAn0n** [comment]
@GitCash send @block-spider 199000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/21/image.png)](https://gitcash.io/claim/block-spider)
@block-spider

**Comment by alwaysAn0n** [comment]
@GitCash send @mikermcneil 100000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/22/image.png)](https://gitcash.io/claim/mikermcneil)
@mikermcneil

**Comment by alwaysAn0n** [comment]
@GitCash send @RX7RUSS 350000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/23/image.png)](https://gitcash.io/claim/RX7RUSS)
@RX7RUSS

**Comment by alwaysAn0n** [comment]
@GitCash send @Quartzic 150000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/24/image.png)](https://gitcash.io/claim/Quartzic)
@Quartzic

**Comment by alwaysAn0n** [comment]
@GitCash send @marfoldi 100000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/25/image.png)](https://gitcash.io/claim/marfoldi)
@marfoldi

**Comment by alwaysAn0n** [comment]
@GitCash send @lte13 100000 satoshis !

Welcome to GitCash!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/26/image.png)](https://gitcash.io/claim/lte13)
@lte13

**Comment by seanwarman** [comment]
Hey @GitCash tip @tj 381960 satoshis for all his great work on Express and exciting recent project Apex.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/27/image.png)](https://gitcash.io/claim/tj)
@tj

**Comment by seanwarman** [comment]
Yo @GitCash give 381960 satoshis to @yyx990803 for making Vue.js the best JS framework there is!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/28/image.png)](https://gitcash.io/claim/yyx990803)
@yyx990803

**Comment by seanwarman** [comment]
Hey @GitCash pay @sindresorhus 381960 satoshis for making some of the best open source apps around. ps. mucho love for Gifski.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/29/image.png)](https://gitcash.io/claim/sindresorhus)
@sindresorhus

**Comment by seanwarman** [comment]
@GitCash tip 381960 satoshis to @zcbenz for his great work on the Atom editor, which is awesome!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/30/image.png)](https://gitcash.io/claim/zcbenz)
@zcbenz

**Comment by seanwarman** [comment]
@GitCash give @rauchg 381960 satoshis for his excellent micro tools.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/31/image.png)](https://gitcash.io/claim/rauchg)
@rauchg

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @laanwj for his great work at Bitcoin XT.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/32/image.png)](https://gitcash.io/claim/laanwj)
@laanwj

**Comment by seanwarman** [comment]
@GitCash give another 381960 satoshis to @laanwj for his work at Bitcoin Unlimited!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/33/image.png)](https://gitcash.io/claim/laanwj)
@laanwj

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @indutny for his work on one the best named node protocols going!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/34/image.png)](https://gitcash.io/claim/indutny)
@indutny

**Comment by seanwarman** [comment]
@GitCash pay @diracdeltas 381960 satoshis for working on Brave, which is the most exciting new browser to hit the internet.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/35/image.png)](https://gitcash.io/claim/diracdeltas)
@diracdeltas

**Comment by seanwarman** [comment]
@GitCash give @jserv 381960 satoshis for showing people how exciting it is to build with build-your-own-x

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/36/image.png)](https://gitcash.io/claim/jserv)
@jserv

**Comment by seanwarman** [comment]
@GitCash send our old buddy @mikermcneil 381960 satoshis for the best framework there is, Sails.js!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/37/image.png)](https://gitcash.io/claim/mikermcneil)
@mikermcneil

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @HelloZeroNet for some really exciting new tech!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/38/image.png)](https://gitcash.io/claim/HelloZeroNet)
@HelloZeroNet

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @samaaron for his brilliant music app sonic-pi.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/39/image.png)](https://gitcash.io/claim/samaaron)
@samaaron

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @maraoz for some great movement in the crypto space.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/40/image.png)](https://gitcash.io/claim/maraoz)
@maraoz

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @trekhleb for his work in opening up the coding world.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/41/image.png)](https://gitcash.io/claim/trekhleb)
@trekhleb

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @caesar0301 for some seriously awesome lists.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/42/image.png)](https://gitcash.io/claim/caesar0301)
@caesar0301

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @maran for some excellent work in the crypto space.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/43/image.png)](https://gitcash.io/claim/maran)
@maran

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @tschellenbach because everybody loves podcasts!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/44/image.png)](https://gitcash.io/claim/tschellenbach)
@tschellenbach

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @leto for his work in the crypto space.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/45/image.png)](https://gitcash.io/claim/leto)
@leto

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @martindale for his work in the crypto space.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/46/image.png)](https://gitcash.io/claim/martindale)
@martindale

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @prusnak , please update Trezor to accept the Cashaddr format!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/47/image.png)](https://gitcash.io/claim/prusnak)
@prusnak

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @abrkn for his excellent work in the crypto space.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/48/image.png)](https://gitcash.io/claim/abrkn)
@abrkn

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @matiu for his great work in the BCH camp!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/49/image.png)](https://gitcash.io/claim/matiu)
@matiu

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @deepthawtz brought to you by Bitbox-Cli :)

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/50/image.png)](https://gitcash.io/claim/deepthawtz)
@deepthawtz

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @AllienWorks cos everybody loves crypto icons!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/51/image.png)](https://gitcash.io/claim/AllienWorks)
@AllienWorks

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @T-Pham for a brilliant implementation of the (otherwise useless) macbook touch bar. Please make some more :)

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/52/image.png)](https://gitcash.io/claim/T-Pham)
@T-Pham

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @sickpig for his great work in the crypto space.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/53/image.png)](https://gitcash.io/claim/sickpig)
@sickpig

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @dsmurrell for his awesome awesome-bitcoin-cash list which is totally awesome.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/54/image.png)](https://gitcash.io/claim/dsmurrell)
@dsmurrell

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @benjamn because the more javascript the better!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/55/image.png)](https://gitcash.io/claim/benjamn)
@benjamn

**Comment by seanwarman** [comment]
@GitCash send 381960 satoshis to @jeresig because evrybody loves jquery.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/56/image.png)](https://gitcash.io/claim/jeresig)
@jeresig

**Comment by seanwarman** [comment]
@GitCash send 0.00375429 bch to @jeresig because everybody loves jquery.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/57/image.png)](https://gitcash.io/claim/jeresig)
@jeresig

**Comment by seanwarman** [comment]
@GitCash send 0.00375 bch to @jeresig because everybody loves jquery.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/58/image.png)](https://gitcash.io/claim/jeresig)
@jeresig

**Comment by seanwarman** [comment]
@GitCash send 0.0037 bch to @diracdeltas for Brave, the best browser on the web!

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/92/image.png)](https://gitcash.io/claim/diracdeltas)
@diracdeltas

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @melchoir55

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/96/image.png)](https://gitcash.io/claim/melchoir55)
@melchoir55

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @superosku

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/97/image.png)](https://gitcash.io/claim/superosku)
@superosku

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @SMR39

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/98/image.png)](https://gitcash.io/claim/SMR39)
@SMR39

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @ttolvane

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/99/image.png)](https://gitcash.io/claim/ttolvane)
@ttolvane

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @neelanand

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/100/image.png)](https://gitcash.io/claim/neelanand)
@neelanand

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @andersrex

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/101/image.png)](https://gitcash.io/claim/andersrex)
@andersrex

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @aleks-betterdoctor

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/102/image.png)](https://gitcash.io/claim/aleks-betterdoctor)
@aleks-betterdoctor

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @IiroIsotalo

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/103/image.png)](https://gitcash.io/claim/IiroIsotalo)
@IiroIsotalo

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @palan3n

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/104/image.png)](https://gitcash.io/claim/palan3n)
@palan3n

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @rubocoptero

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/105/image.png)](https://gitcash.io/claim/rubocoptero)
@rubocoptero

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @skogstrom

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/106/image.png)](https://gitcash.io/claim/skogstrom)
@skogstrom

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @paulwhitaker

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/107/image.png)](https://gitcash.io/claim/paulwhitaker)
@paulwhitaker

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @stevebestest

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/108/image.png)](https://gitcash.io/claim/stevebestest)
@stevebestest

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @sojackyso

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/109/image.png)](https://gitcash.io/claim/sojackyso)
@sojackyso

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @melindaheard

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/110/image.png)](https://gitcash.io/claim/melindaheard)
@melindaheard

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @dinkostka

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/111/image.png)](https://gitcash.io/claim/dinkostka)
@dinkostka

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @dinkostka

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/112/image.png)](https://gitcash.io/claim/dinkostka)
@dinkostka

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @nebojsa007

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/113/image.png)](https://gitcash.io/claim/nebojsa007)
@nebojsa007

**Comment by deepthawtz** [comment]
@GitCash send 100000 satoshis to @sassanuv

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/114/image.png)](https://gitcash.io/claim/sassanuv)
@sassanuv

**Comment by dsmurrell** [comment]
@seanwarman, thanks for the tip! Can't really find it anymore in this thread, but I seem to remember that it was you who tipped me.

**Comment by seanwarman** [comment]
I seem to remember tipping you too. Don't worry, if you go to https://gitcash.io you can log in with your GitHub account and the money should be waiting for you.

**Comment by dsmurrell** [comment]
@seanwarman, added GitCash to [awesome-bitcoin-cash](https://github.com/dsmurrell/awesome-bitcoin-cash/blob/master/README.md). Do you work for GitCash? Let me know if it's fine as is.

**Comment by seanwarman** [comment]
Thanks @dsmurrell that's great. I'm a part of the team that developed GitCash yes.

**Comment by seanwarman** [comment]
@GitCash test that 0.00010 bch @alwaysAn0n pretty please

**Comment by GitCash** [comment]
Hey **alwaysAn0n**, user **seanwarman** tipped you **100 bits** in Bitcoin Cash ( ~ **$0.0714** ).

*[Click here to claim it!](https://gitcash.io/claim/alwaysAn0n)*

You can also add the :-1: reaction to **seanwarman**'s comment above to prevent future tips.

**Comment by alwaysAn0n** [comment]
@GitCash send @kodaxx 10 dollars to test his new BCH wallet!

**Comment by GitCash** [comment]
Hey **kodaxx**, user **alwaysAn0n** tipped you **14347 bits** in Bitcoin Cash ( ~ **$10** ).

*[Click here to claim it!](https://gitcash.io/claim/kodaxx)*

You can also add the :-1: reaction to **alwaysAn0n**'s comment above to prevent future tips.
