### ISSUE TITLE
Tipping in bits seems to give wrong text output

### ISSUE THREAD

**Issue by tbitu** [GitCash/issues-and-feature-requests#6]
As mentioned on reddit - tipped 15000 bits and the GitCash response was 
"AstarothPoD sent you 15 bits in Bitcoin Cash - that's 1500000 satoshis ( ~$11.52 )

The right amount was tipped, so just a text error in the "bits" calculation it seems.

Thanks for making this fantastic GitHub functionality!

**Comment by alwaysAn0n** [comment]
This turned out to be a big in the code that generates the tip response image.  We removed the tip response image and fixed this code in our most recent release.  Thanks for your help identifying it!

@GitCash please reward @AstarothPoD with 10 dollars for being a true patriot

**Comment by GitCash** [comment]
Hey **AstarothPoD**, user **alwaysAn0n** tipped you **14471 bits** in Bitcoin Cash ( ~ **$10** ).

*[Click here to claim it!](https://gitcash.io/claim/AstarothPoD)*

You can also add the :-1: reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by GitCash** [comment]
Solved!
