### ISSUE TITLE
It's not breakfast without eggs

### ISSUE THREAD

**Issue by alwaysAn0n** [GitCash/issues-and-feature-requests#8]
Hey @GotCrabs send @ConsensusBot $.25 please

**Comment by GotCrabs** [comment]
Hey **ConsensusBot**, user **alwaysAn0n** tipped you **2212 bits** in Bitcoin Cash ( ~ **$0.25** ).

*[Click here to claim it!](https://gitcash-staging.herokuapp.com/claim/ConsensusBot)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by alwaysAn0n** [comment]
Hey @GotCrabs send @ConsensusBot $.75 now!

**Comment by GotCrabs** [comment]
Hey **ConsensusBot**, user **alwaysAn0n** tipped you **6696 bits** in Bitcoin Cash ( ~ **$0.75** ).

*[Click here to claim it!](https://gitcash-staging.herokuapp.com/claim/ConsensusBot)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.

**Comment by alwaysAn0n** [comment]
Hey @GotCrabs send @ConsensusBot .25 usd please

**Comment by GotCrabs** [comment]
Hey **ConsensusBot**, user **alwaysAn0n** tipped you **2380 bits** in Bitcoin Cash ( ~ **$0.25** ).

*[Click here to claim it!](https://gitcash-staging.herokuapp.com/claim/ConsensusBot)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.
